spring:
  application:
    name: ai-agent-service
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:ai-agent-service:8084 # Forcefully kills ZORO_PC text strings in the metadata registry
    hostname: 127.0.0.1